zuul:
  routes:
    book:
      path: /travel/**
      url: http://localhost:8080
    movie:
      path: /movie/something/**
      url: http://localhost:8080
ribbon:
  eureka:
    enabled: true
    client:
      registerWithEureka: true
      serviceUrl:
        region: zone2
        availability-zones:
          zone1: peer1,peer2
          zone2: peer2,peer1
        serviceUrl:
          peer1: http://localhost:8761/eureka/
          peer2: http://localhost:8762/eureka/
        defaultZone: http://localhost:8762/eureka/
  
 # listOfServers: localhost:8080 
server:
  port: 9000